route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telepush'

receivers:
  - name: 'telepush'
    webhook_configs:
    - url: 'https://telepush.dev/api/inlets/alertmanager/f28d4a'
      http_config:

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']


curl -XPOST \
   -d '{ "text": "ГООЙДА" }' \
   https://telepush.dev/api/inlets/alertmanager/f28d4a